// This file is generated by Sapper — do not edit it!
export const timestamp = 1551535357769;

export const files = [
	"/service-worker-index.html",
	"ace-logo-192.png",
	"ace-logo-512.png",
	"favicon.png",
	"global.css",
	"manifest.json"
];
export { files as assets }; // legacy

export const shell = [
	"client/chunk.589ec022.js",
	"client/client.a5fd552e.js",
	"client/chunk.acbbc4d0.js"
];

export const routes = [
	{ pattern: /^\/?$/ }
];