// This file is generated by Sapper — do not edit it!
export const timestamp = 1544983424872;

export const files = [
	"ace-logo-192.png",
	"ace-logo-512.png",
	"favicon.png",
	"global.css",
	"manifest.json"
];
export { files as assets }; // legacy

export const shell = [
	"client/0283a0fd0939bbb49a77/0.0.js",
	"client/0283a0fd0939bbb49a77/index.index.js",
	"client/0283a0fd0939bbb49a77/main.js"
];

export const routes = [
	{ pattern: /^\/?$/ }
];