import type {
  Afternoon,
  Day,
  Inspection,
  Inspections,
  Interval,
  Intervals,
  Morning,
  Period,
  Periods,
} from "../src/lib/Types";
import { Type } from "../src/lib/Types";

import { TEXT } from "../src/data/Data";

export const morning: {
  on: Morning;
  off: Morning;
} = {
  on: {
    active: true,
    begin: "08:40",
    end: "11:20",
  },
  off: {
    active: false,
    begin: "08:40",
    end: "11:20",
  },
};

export const afternoon: {
  on: Afternoon;
  off: Afternoon;
} = {
  on: {
    active: true,
    begin: "14:20",
    end: "17:20",
  },
  off: {
    active: false,
    begin: "14:20",
    end: "17:20",
  },
};

export const periods: {
  fullday: {
    first: Period;
    second: Period;
  };
  first: Period;
  second: Period;
} = {
  fullday: {
    first: {
      index: 0,
      start: 31200000,
      stop: 40800000,
      span: 9600000,
    },
    second: {
      index: 1,
      start: 51600000,
      stop: 62400000,
      span: 10800000,
    },
  },
  first: {
    index: 0,
    start: 31200000,
    stop: 40800000,
    span: 9600000,
  },
  second: {
    index: 0,
    start: 51600000,
    stop: 62400000,
    span: 10800000,
  },
};

export const intervals: {
  lunchOnly: { list: Intervals };
  rainOnly: { list: Intervals };
  lunchAndRain: { list: Intervals };
  lunchAndRains: { list: Intervals };
} = {
  lunchOnly: {
    list: [
      {
        type: Type.Lunch,
        start: 40800000,
        stop: 51600000,
      },
    ],
  },
  rainOnly: {
    list: [
      {
        type: Type.Rain,
        start: 33000000,
        stop: 36120000,
      },
    ],
  },
  lunchAndRain: {
    list: [
      {
        type: Type.Rain,
        start: 33000000,
        stop: 36120000,
      },
      {
        type: Type.Lunch,
        start: 40800000,
        stop: 51600000,
      },
    ],
  },
  lunchAndRains: {
    list: [
      {
        type: Type.Rain,
        start: 33000000,
        stop: 36120000,
      },
      {
        type: Type.Rain,
        start: 38100000,
        stop: 39600000,
      },
      {
        type: Type.Lunch,
        start: 40800000,
        stop: 51600000,
      },
      {
        type: Type.Rain,
        start: 55320000,
        stop: 58140000,
      },
    ],
  },
};

export const inspections: {
  emptyDay: {
    list: Inspections;
    normal: number;
    closed: number;
    recovered: number;
  };
  normalDay: {
    list: Inspections;
    normal: number;
    closed: number;
    recovered: number;
  };
  normalDayRecovered: {
    list: Inspections;
    normal: number;
    closed: number;
    recovered: number;
  };
  manyClosed: {
    list: Inspections;
    normal: number;
    closed: number;
    recovered: number;
  };
} = {
  emptyDay: {
    list: [],
    normal: 0,
    closed: 0,
    recovered: 0,
  },
  normalDay: {
    list: [
      {
        index: 0,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 1,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 2,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 3,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 4,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 5,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 6,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 7,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 8,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 9,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 10,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 11,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 12,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 13,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 14,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 15,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 16,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 17,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 18,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 19,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 20,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 21,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 22,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 23,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 24,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 25,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 26,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 27,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 28,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 29,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 30,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 31,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 32,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 33,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 34,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
    ],
    normal: 20,
    closed: 15,
    recovered: 0,
  },
  normalDayRecovered: {
    list: [
      {
        index: 0,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 1,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 2,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 3,
        type: Type.Recovered,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 4,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 5,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 6,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 7,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 8,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 9,
        type: Type.Recovered,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 10,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 11,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 12,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 13,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 14,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 15,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 16,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 17,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 18,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 19,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 20,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 21,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 22,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 23,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 24,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 25,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 26,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 27,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 28,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 29,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 30,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 31,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 32,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 33,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 34,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
    ],
    normal: 20,
    closed: 13,
    recovered: 2,
  },
  manyClosed: {
    list: [
      {
        index: 0,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 1,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 2,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 3,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 4,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 5,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 6,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 7,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 8,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 9,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 10,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 11,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 12,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 13,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 14,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 15,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 16,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 17,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 18,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 19,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 20,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 21,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 22,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 23,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 24,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 25,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 26,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 27,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 28,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 29,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 30,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 31,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 32,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 33,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 34,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
    ],
    normal: 12,
    closed: 23,
    recovered: 0,
  },
};

export const report: {
  emptyDay: {
    list: Inspections;
    normal: number;
    closed: number;
    recovered: number;
  };
  normalDay: {
    list: Inspections;
    normal: number;
    closed: number;
    recovered: number;
  };
  normalDayRecovered: {
    list: Inspections;
    normal: number;
    closed: number;
    recovered: number;
  };
  manyClosed: {
    list: Inspections;
    normal: number;
    closed: number;
    recovered: number;
  };
} = {
  emptyDay: {
    list: [],
    normal: 0,
    closed: 0,
    recovered: 0,
  },
  normalDay: {
    list: [
      {
        index: 0,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 1,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 2,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 3,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 4,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 5,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 6,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 7,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 8,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 9,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 10,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 11,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 12,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 13,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 14,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 15,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 16,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 17,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 18,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 19,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 20,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 21,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 22,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 23,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 24,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 25,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 26,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 27,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 28,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 29,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 30,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 31,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 32,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 33,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 34,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
    ],
    normal: 20,
    closed: 15,
    recovered: 0,
  },
  normalDayRecovered: {
    list: [
      {
        index: 0,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 1,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 2,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 3,
        type: Type.Recovered,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 4,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 5,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 6,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 7,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 8,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 9,
        type: Type.Recovered,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 10,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 11,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 12,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 13,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 14,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 15,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 16,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 17,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 18,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 19,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 20,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 21,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 22,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 23,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 24,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 25,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 26,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 27,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 28,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 29,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 30,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 31,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 32,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 33,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 34,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
    ],
    normal: 20,
    closed: 13,
    recovered: 2,
  },
  manyClosed: {
    list: [
      {
        index: 0,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 1,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 2,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 3,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 4,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 5,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 6,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 7,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 8,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 9,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 10,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 11,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 12,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 13,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 14,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 15,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 16,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 17,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 18,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 19,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 20,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 21,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 22,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 23,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 24,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 25,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 26,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 27,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 28,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 29,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 30,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 31,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 32,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 33,
        type: Type.Closed,
        period: 0,
        start: 0,
        stop: 0,
      },
      {
        index: 34,
        type: Type.Normal,
        period: 0,
        start: 0,
        stop: 0,
      },
    ],
    normal: 12,
    closed: 23,
    recovered: 0,
  },
};
